version: "3.8"

services:
 tekanaewalletapp:
  build: .
  restart: always
  ports:
   - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}
   SPRING_DATASOURCE_USERNAME: ${MYSQLDB_ROOT_USER}
   SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
  depends_on:
   - mysqldb
 mysqldb:
  platform: linux/x86_64
  image: "mysql:5.7"
  restart: always
  ports:
   - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
  environment:
   MYSQL_DATABASE: ${MYSQLDB_DATABASE}
   MYSQL_USER: ${MYSQLDB_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}