spring:
  datasource:
   #url: jdbc:mysql://mysqldb:3306/tekanaewallet
   url: jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}
   username: ${MYSQLDB_ROOT_USER}
   password: ${MYSQLDB_ROOT_PASSWORD}

  #JPA Settings
  # Log SQL statements
  jpa.show-sql: true
  # Hibernate database Dialect
  #jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  # Hibernate ddl auto for generating the database schema
  jpa.hibernate.ddl_auto: update

#spring swagger configuration
#springdoc:
#  swagger-ui:
#    enabled: true