spring:
  datasource:
   url: jdbc:mysql://mysqldb:3306/tekanaewallet
   username: root
   password: Rra@123.123

  #JPA Settings
  # Log SQL statements
  jpa.show-sql: true
  # Hibernate database Dialect
  #jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  # Hibernate ddl auto for generating the database schema
  jpa.hibernate.ddl_auto: update

#spring swagger configuration
#springdoc:
#  swagger-ui:
#    enabled: true